DELETE http://localhost:3003/api/blogs/64c23e83f6c88c9abcc61b57
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF6aXoiLCJpZCI6IjY0YzAyZGZjNGY1YzgzZDM2MzkxMDM1MyIsImlhdCI6MTY5MDQ0OTM1MywiZXhwIjoxNjkwNDUyOTUzfQ.WU8V_p81u_6VbjiWSeE3aXgAOxtU0GBEKjcySQAIz3U
